"""remove type column

Revision ID: 90d113c6bf2e
Revises: be106ae87a64
Create Date: 2025-08-19 15:54:55.935498

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "90d113c6bf2e"
down_revision = "be106ae87a64"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.drop_column("type")

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("products", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("type", sa.VARCHAR(length=20), autoincrement=False, nullable=True)
        )

    # ### end Alembic commands ###
