"""Inital migrations with Products and User model

Revision ID: a097c1005b66
Revises:
Create Date: 2025-08-25 12:39:52.093506

"""

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = "a097c1005b66"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("product_name", sa.String(length=50), nullable=False),
        sa.Column("category", sa.String(length=20), nullable=False),
        sa.Column("quantity", sa.Integer(), nullable=False),
        sa.Column("price", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("username", sa.String(length=50), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("id"),
        sa.UniqueConstraint("username"),
    )
    op.create_table(
        "book_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("author", sa.String(length=50), nullable=False),
        sa.Column("publication_year", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "electronic_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("purchase_date", sa.Date(), nullable=False),
        sa.Column("warranty_period", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "food_products",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("mfg_date", sa.Date(), nullable=False),
        sa.Column("expiry_date", sa.Date(), nullable=False),
        sa.ForeignKeyConstraint(
            ["id"],
            ["products.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("food_products")
    op.drop_table("electronic_products")
    op.drop_table("book_products")
    op.drop_table("users")
    op.drop_table("products")
    # ### end Alembic commands ###
