"""Add owner_id to products serializer

Revision ID: c45795734c03
Revises: 2942838aa73d
Create Date: 2025-08-29 16:41:42.683236

"""

from alembic import op

# revision identifiers, used by Alembic.
revision = "c45795734c03"
down_revision = "2942838aa73d"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_unique_constraint(None, ["id"])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_constraint(None, type_="unique")

    # ### end Alembic commands ###
