"""add user_documents table

Revision ID: 2ac312a57103
Revises: ebc0176adc40
Create Date: 2025-09-15 10:33:48.567767

"""

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = "2ac312a57103"
down_revision = "ebc0176adc40"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "user_documents",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("filename", sa.String(length=255), nullable=False),
        sa.Column("owner_id", sa.UUID(), nullable=True),
        sa.Column("visibility", sa.String(length=32), nullable=False),
        sa.Column("content_type", sa.String(length=64), nullable=True),
        sa.Column("size", sa.Integer(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=True,
        ),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=True),
        sa.ForeignKeyConstraint(
            ["owner_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_documents", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_user_documents_id"), ["id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_user_documents_owner_id"), ["owner_id"], unique=False
        )

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "langchain_pg_collection",
        sa.Column("name", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "cmetadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.PrimaryKeyConstraint("uuid", name="langchain_pg_collection_pkey"),
        postgresql_ignore_search_path=False,
    )
    op.create_table(
        "documents",
        sa.Column("id", sa.INTEGER(), autoincrement=True, nullable=False),
        sa.Column("content", sa.TEXT(), autoincrement=False, nullable=True),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.PrimaryKeyConstraint("id", name=op.f("documents_pkey")),
    )
    op.create_table(
        "langchain_pg_embedding",
        sa.Column("collection_id", sa.UUID(), autoincrement=False, nullable=True),
        sa.Column("embedding", sa.NullType(), autoincrement=False, nullable=True),
        sa.Column("document", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column(
            "cmetadata",
            postgresql.JSON(astext_type=sa.Text()),
            autoincrement=False,
            nullable=True,
        ),
        sa.Column("custom_id", sa.VARCHAR(), autoincrement=False, nullable=True),
        sa.Column("uuid", sa.UUID(), autoincrement=False, nullable=False),
        sa.ForeignKeyConstraint(
            ["collection_id"],
            ["langchain_pg_collection.uuid"],
            name=op.f("langchain_pg_embedding_collection_id_fkey"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("uuid", name=op.f("langchain_pg_embedding_pkey")),
    )
    with op.batch_alter_table("user_documents", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_documents_owner_id"))
        batch_op.drop_index(batch_op.f("ix_user_documents_id"))

    op.drop_table("user_documents")
    # ### end Alembic commands ###
