"""Add LLMCache table

Revision ID: 31e484e25787
Revises: c45795734c03
Create Date: 2025-09-08 13:23:44.630911

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "31e484e25787"
down_revision = "c45795734c03"
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "llm_cache",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=True),
        sa.Column("model", sa.String(length=50), nullable=False),
        sa.Column("prompt", sa.Text(), nullable=False),
        sa.Column("response", sa.Text(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("llm_cache", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_llm_cache_created_at"), ["created_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_llm_cache_id"), ["id"], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("llm_cache", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_llm_cache_id"))
        batch_op.drop_index(batch_op.f("ix_llm_cache_created_at"))

    op.drop_table("llm_cache")
    # ### end Alembic commands ###
